codecov:
  notify:
    require_ci_to_pass: no
    
  coverage:
    precision: 2
    round: nearest
    range: "60...90"
    
  status:
    project: yes
    patch: yes
    
    ignore:
      - "adocs" 
      - "coverage"
	  - "./src/lib/datasync.js"